-- Little Wins — single-owner Supabase schema
-- All anonymous browser sessions share one private-app profile.
-- Run this entire file in the Supabase SQL Editor after deploying the matching frontend files.

create extension if not exists pgcrypto;

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique default '00000000-0000-0000-0000-000000000001'::uuid,
  reward_name text not null default 'Blind Pack' check (char_length(reward_name) between 1 and 80),
  target_days integer not null default 7 check (target_days between 1 and 365),
  theme text not null default 'sakura' check (theme in ('sakura', 'strawberry', 'lavender', 'peach', 'bubblegum')),
  daily_reminder_time time without time zone not null default '20:00',
  show_celebration boolean not null default true,
  enable_sound boolean not null default true,
  current_streak integer not null default 0 check (current_streak >= 0),
  best_streak integer not null default 0 check (best_streak >= 0),
  total_checkins integer not null default 0 check (total_checkins >= 0),
  total_no_spend integer not null default 0 check (total_no_spend >= 0),
  total_spend integer not null default 0 check (total_spend >= 0),
  total_rewards integer not null default 0 check (total_rewards >= 0),
  last_checkin_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001'::uuid,
  log_date date not null,
  status text not null check (status in ('no_spend', 'spent')),
  created_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001'::uuid,
  earned_date date not null,
  reward_name text not null check (char_length(reward_name) between 1 and 80),
  streak_length integer not null check (streak_length > 0),
  claimed boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001'::uuid,
  achievement_key text not null check (achievement_key in (
    'first_checkin',
    'first_reward',
    'seven_day_streak',
    'thirty_no_spend',
    'ten_rewards',
    'hundred_checkins'
  )),
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_key)
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null default '00000000-0000-0000-0000-000000000001'::uuid,
  name text not null check (char_length(name) between 1 and 120),
  category text check (category is null or char_length(category) <= 60),
  priority smallint not null default 2 check (priority between 1 and 3),
  owned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_logs_user_date_idx on public.daily_logs (user_id, log_date desc);
create index if not exists daily_logs_user_status_idx on public.daily_logs (user_id, status);
create index if not exists rewards_user_date_idx on public.rewards (user_id, earned_date desc);
create index if not exists achievements_user_unlocked_idx on public.achievements (user_id, unlocked_at desc);
create index if not exists wishlist_user_owned_idx on public.wishlist (user_id, owned, created_at desc);
create index if not exists wishlist_user_name_idx on public.wishlist (user_id, lower(name));

-- Convert an existing per-device anonymous installation into one shared profile.
-- The profile with the most check-ins is preserved; other accidental anonymous
-- profiles are removed. Re-running this file is safe.
alter table public.settings drop constraint if exists settings_user_id_fkey;
alter table public.daily_logs drop constraint if exists daily_logs_user_id_fkey;
alter table public.rewards drop constraint if exists rewards_user_id_fkey;
alter table public.achievements drop constraint if exists achievements_user_id_fkey;
alter table public.wishlist drop constraint if exists wishlist_user_id_fkey;

alter table public.settings alter column user_id set default '00000000-0000-0000-0000-000000000001'::uuid;
alter table public.daily_logs alter column user_id set default '00000000-0000-0000-0000-000000000001'::uuid;
alter table public.rewards alter column user_id set default '00000000-0000-0000-0000-000000000001'::uuid;
alter table public.achievements alter column user_id set default '00000000-0000-0000-0000-000000000001'::uuid;
alter table public.wishlist alter column user_id set default '00000000-0000-0000-0000-000000000001'::uuid;

do $$
declare
  v_owner_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_source_id uuid;
begin
  select user_id
  into v_source_id
  from public.settings
  order by (user_id = v_owner_id) desc, total_checkins desc, updated_at desc
  limit 1;

  if v_source_id is null then
    insert into public.settings (user_id) values (v_owner_id);
  else
    delete from public.daily_logs where user_id <> v_source_id;
    delete from public.rewards where user_id <> v_source_id;
    delete from public.achievements where user_id <> v_source_id;
    delete from public.wishlist where user_id <> v_source_id;
    delete from public.settings where user_id <> v_source_id;

    if v_source_id <> v_owner_id then
      update public.daily_logs set user_id = v_owner_id where user_id = v_source_id;
      update public.rewards set user_id = v_owner_id where user_id = v_source_id;
      update public.achievements set user_id = v_owner_id where user_id = v_source_id;
      update public.wishlist set user_id = v_owner_id where user_id = v_source_id;
      update public.settings set user_id = v_owner_id where user_id = v_source_id;
    end if;
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

drop trigger if exists wishlist_set_updated_at on public.wishlist;
create trigger wishlist_set_updated_at
before update on public.wishlist
for each row execute function public.set_updated_at();

-- Single-owner mode does not create one profile per anonymous Auth user.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create or replace function public.ensure_user_profile()
returns public.settings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_settings public.settings%rowtype;
begin
  insert into public.settings (user_id)
  values (v_owner_id)
  on conflict (user_id) do nothing;

  select * into v_settings
  from public.settings
  where user_id = v_owner_id;

  return v_settings;
end;
$$;

create or replace function public.unlock_achievements(p_user_id uuid)
returns text[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.settings%rowtype;
  v_unlocked text[] := array[]::text[];
  v_rows integer;
begin
  select * into v_settings
  from public.settings
  where user_id = p_user_id;

  if not found then
    return v_unlocked;
  end if;

  if v_settings.total_checkins >= 1 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'first_checkin')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'first_checkin'); end if;
  end if;

  if v_settings.total_rewards >= 1 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'first_reward')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'first_reward'); end if;
  end if;

  if v_settings.best_streak >= 7 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'seven_day_streak')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'seven_day_streak'); end if;
  end if;

  if v_settings.total_no_spend >= 30 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'thirty_no_spend')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'thirty_no_spend'); end if;
  end if;

  if v_settings.total_rewards >= 10 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'ten_rewards')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'ten_rewards'); end if;
  end if;

  if v_settings.total_checkins >= 100 then
    insert into public.achievements (user_id, achievement_key)
    values (p_user_id, 'hundred_checkins')
    on conflict (user_id, achievement_key) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows > 0 then v_unlocked := array_append(v_unlocked, 'hundred_checkins'); end if;
  end if;

  return v_unlocked;
end;
$$;

create or replace function public.check_in(
  p_status text,
  p_log_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_settings public.settings%rowtype;
  v_run_streak integer;
  v_best_streak integer;
  v_earned_reward boolean := false;
  v_newly_unlocked text[] := array[]::text[];
begin
  if p_status not in ('no_spend', 'spent') then
    raise exception 'INVALID_STATUS';
  end if;

  -- A browser-local date can differ from UTC by one calendar day.
  if p_log_date is null or p_log_date < current_date - 1 or p_log_date > current_date + 1 then
    raise exception 'INVALID_LOG_DATE';
  end if;

  perform public.ensure_user_profile();

  select * into v_settings
  from public.settings
  where user_id = v_user_id
  for update;

  if exists (
    select 1 from public.daily_logs
    where user_id = v_user_id and log_date = p_log_date
  ) then
    raise exception 'ALREADY_CHECKED_IN';
  end if;

  insert into public.daily_logs (user_id, log_date, status)
  values (v_user_id, p_log_date, p_status);

  if p_status = 'no_spend' then
    if v_settings.last_checkin_date = p_log_date - 1 then
      v_run_streak := v_settings.current_streak + 1;
    else
      v_run_streak := 1;
    end if;

    v_best_streak := greatest(v_settings.best_streak, v_run_streak);

    if v_run_streak >= v_settings.target_days then
      insert into public.rewards (user_id, earned_date, reward_name, streak_length)
      values (v_user_id, p_log_date, v_settings.reward_name, v_run_streak);

      update public.settings
      set current_streak = 0,
          best_streak = v_best_streak,
          total_checkins = total_checkins + 1,
          total_no_spend = total_no_spend + 1,
          total_rewards = total_rewards + 1,
          last_checkin_date = p_log_date
      where user_id = v_user_id;

      v_earned_reward := true;
    else
      update public.settings
      set current_streak = v_run_streak,
          best_streak = v_best_streak,
          total_checkins = total_checkins + 1,
          total_no_spend = total_no_spend + 1,
          last_checkin_date = p_log_date
      where user_id = v_user_id;
    end if;
  else
    update public.settings
    set current_streak = 0,
        total_checkins = total_checkins + 1,
        total_spend = total_spend + 1,
        last_checkin_date = p_log_date
    where user_id = v_user_id;
  end if;

  v_newly_unlocked := public.unlock_achievements(v_user_id);

  select * into v_settings
  from public.settings
  where user_id = v_user_id;

  return jsonb_build_object(
    'status', p_status,
    'log_date', p_log_date,
    'earned_reward', v_earned_reward,
    'reward_name', case when v_earned_reward then v_settings.reward_name else null end,
    'current_streak', v_settings.current_streak,
    'best_streak', v_settings.best_streak,
    'total_rewards', v_settings.total_rewards,
    'newly_unlocked', to_jsonb(v_newly_unlocked)
  );
exception
  when unique_violation then
    raise exception 'ALREADY_CHECKED_IN';
end;
$$;

drop function if exists public.get_statistics();

create or replace function public.get_statistics(p_local_date date default current_date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_settings public.settings%rowtype;
  v_success_rate numeric := 0;
  v_longest_month text;
  v_current_month jsonb;
  v_monthly_history jsonb;
begin
  if p_local_date is null or p_local_date < current_date - 1 or p_local_date > current_date + 1 then
    raise exception 'INVALID_LOCAL_DATE';
  end if;

  perform public.ensure_user_profile();

  select * into v_settings
  from public.settings
  where user_id = v_user_id;

  if v_settings.total_checkins > 0 then
    v_success_rate := round((v_settings.total_no_spend::numeric / v_settings.total_checkins::numeric) * 100, 1);
  end if;

  select to_char(month_start, 'FMMonth YYYY')
  into v_longest_month
  from (
    select date_trunc('month', log_date)::date as month_start,
           count(*) filter (where status = 'no_spend') as no_spend_count
    from public.daily_logs
    where user_id = v_user_id
    group by 1
    order by no_spend_count desc, month_start desc
    limit 1
  ) ranked_month;

  select jsonb_build_object(
    'no_spend', count(*) filter (where status = 'no_spend'),
    'spent', count(*) filter (where status = 'spent'),
    'total', count(*),
    'success_rate', case
      when count(*) = 0 then 0
      else round((count(*) filter (where status = 'no_spend'))::numeric / count(*)::numeric * 100, 1)
    end
  )
  into v_current_month
  from public.daily_logs
  where user_id = v_user_id
    and log_date >= date_trunc('month', p_local_date)::date
    and log_date < (date_trunc('month', p_local_date) + interval '1 month')::date;

  with months as (
    select generate_series(
      date_trunc('month', p_local_date) - interval '5 months',
      date_trunc('month', p_local_date),
      interval '1 month'
    )::date as month_start
  ), counts as (
    select date_trunc('month', log_date)::date as month_start,
           count(*) filter (where status = 'no_spend') as no_spend,
           count(*) filter (where status = 'spent') as spent
    from public.daily_logs
    where user_id = v_user_id
      and log_date >= date_trunc('month', p_local_date) - interval '5 months'
    group by 1
  )
  select jsonb_agg(
    jsonb_build_object(
      'month', to_char(months.month_start, 'YYYY-MM'),
      'label', to_char(months.month_start, 'Mon'),
      'no_spend', coalesce(counts.no_spend, 0),
      'spent', coalesce(counts.spent, 0)
    )
    order by months.month_start
  )
  into v_monthly_history
  from months
  left join counts using (month_start);

  return jsonb_build_object(
    'current_streak', v_settings.current_streak,
    'best_streak', v_settings.best_streak,
    'total_checkins', v_settings.total_checkins,
    'total_no_spend', v_settings.total_no_spend,
    'total_spend', v_settings.total_spend,
    'success_rate', v_success_rate,
    'total_rewards', v_settings.total_rewards,
    'longest_month', v_longest_month,
    'current_month_performance', coalesce(v_current_month, '{}'::jsonb),
    'monthly_history', coalesce(v_monthly_history, '[]'::jsonb)
  );
end;
$$;

create or replace function public.get_backup_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
begin
  return jsonb_build_object(
    'settings', (select to_jsonb(s) - 'id' - 'user_id' from public.settings s where s.user_id = v_user_id),
    'daily_logs', coalesce((select jsonb_agg(to_jsonb(d) - 'user_id' order by d.log_date) from public.daily_logs d where d.user_id = v_user_id), '[]'::jsonb),
    'rewards', coalesce((select jsonb_agg(to_jsonb(r) - 'user_id' order by r.earned_date) from public.rewards r where r.user_id = v_user_id), '[]'::jsonb),
    'achievements', coalesce((select jsonb_agg(to_jsonb(a) - 'user_id' order by a.unlocked_at) from public.achievements a where a.user_id = v_user_id), '[]'::jsonb),
    'wishlist', coalesce((select jsonb_agg(to_jsonb(w) - 'user_id' order by w.created_at) from public.wishlist w where w.user_id = v_user_id), '[]'::jsonb)
  );
end;
$$;


create or replace function public.restore_backup_data(p_backup jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_settings jsonb;
  v_item jsonb;
begin
  if p_backup is null or jsonb_typeof(p_backup) <> 'object' then
    raise exception 'INVALID_BACKUP';
  end if;

  perform public.ensure_user_profile();
  v_settings := coalesce(p_backup -> 'settings', '{}'::jsonb);

  delete from public.daily_logs where user_id = v_user_id;
  delete from public.rewards where user_id = v_user_id;
  delete from public.achievements where user_id = v_user_id;
  delete from public.wishlist where user_id = v_user_id;

  update public.settings
  set reward_name = coalesce(nullif(v_settings ->> 'reward_name', ''), reward_name),
      target_days = coalesce((v_settings ->> 'target_days')::integer, target_days),
      theme = coalesce(nullif(v_settings ->> 'theme', ''), theme),
      daily_reminder_time = coalesce((v_settings ->> 'daily_reminder_time')::time, daily_reminder_time),
      show_celebration = coalesce((v_settings ->> 'show_celebration')::boolean, show_celebration),
      enable_sound = coalesce((v_settings ->> 'enable_sound')::boolean, enable_sound),
      current_streak = greatest(0, coalesce((v_settings ->> 'current_streak')::integer, 0)),
      best_streak = greatest(0, coalesce((v_settings ->> 'best_streak')::integer, 0)),
      last_checkin_date = nullif(v_settings ->> 'last_checkin_date', '')::date
  where user_id = v_user_id;

  for v_item in select value from jsonb_array_elements(coalesce(p_backup -> 'daily_logs', '[]'::jsonb))
  loop
    insert into public.daily_logs (user_id, log_date, status, created_at)
    values (
      v_user_id,
      (v_item ->> 'log_date')::date,
      v_item ->> 'status',
      coalesce((v_item ->> 'created_at')::timestamptz, now())
    )
    on conflict (user_id, log_date) do update set status = excluded.status;
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_backup -> 'rewards', '[]'::jsonb))
  loop
    insert into public.rewards (user_id, earned_date, reward_name, streak_length, claimed, created_at)
    values (
      v_user_id,
      (v_item ->> 'earned_date')::date,
      v_item ->> 'reward_name',
      (v_item ->> 'streak_length')::integer,
      coalesce((v_item ->> 'claimed')::boolean, true),
      coalesce((v_item ->> 'created_at')::timestamptz, now())
    );
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_backup -> 'achievements', '[]'::jsonb))
  loop
    insert into public.achievements (user_id, achievement_key, unlocked_at)
    values (
      v_user_id,
      v_item ->> 'achievement_key',
      coalesce((v_item ->> 'unlocked_at')::timestamptz, now())
    )
    on conflict (user_id, achievement_key) do nothing;
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_backup -> 'wishlist', '[]'::jsonb))
  loop
    insert into public.wishlist (user_id, name, category, priority, owned, created_at, updated_at)
    values (
      v_user_id,
      v_item ->> 'name',
      nullif(v_item ->> 'category', ''),
      coalesce((v_item ->> 'priority')::smallint, 2),
      coalesce((v_item ->> 'owned')::boolean, false),
      coalesce((v_item ->> 'created_at')::timestamptz, now()),
      coalesce((v_item ->> 'updated_at')::timestamptz, now())
    );
  end loop;

  update public.settings s
  set total_checkins = (select count(*) from public.daily_logs d where d.user_id = v_user_id),
      total_no_spend = (select count(*) from public.daily_logs d where d.user_id = v_user_id and d.status = 'no_spend'),
      total_spend = (select count(*) from public.daily_logs d where d.user_id = v_user_id and d.status = 'spent'),
      total_rewards = (select count(*) from public.rewards r where r.user_id = v_user_id)
  where s.user_id = v_user_id;

  return jsonb_build_object('restored', true);
end;
$$;

alter table public.settings enable row level security;
alter table public.daily_logs enable row level security;
alter table public.rewards enable row level security;
alter table public.achievements enable row level security;
alter table public.wishlist enable row level security;

drop policy if exists settings_select_own on public.settings;
create policy settings_select_own on public.settings
for select to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists settings_update_own on public.settings;
create policy settings_update_own on public.settings
for update to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid)
with check (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists daily_logs_select_own on public.daily_logs;
create policy daily_logs_select_own on public.daily_logs
for select to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists rewards_select_own on public.rewards;
create policy rewards_select_own on public.rewards
for select to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists achievements_select_own on public.achievements;
create policy achievements_select_own on public.achievements
for select to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists wishlist_select_own on public.wishlist;
create policy wishlist_select_own on public.wishlist
for select to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists wishlist_insert_own on public.wishlist;
create policy wishlist_insert_own on public.wishlist
for insert to authenticated
with check (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists wishlist_update_own on public.wishlist;
create policy wishlist_update_own on public.wishlist
for update to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid)
with check (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

drop policy if exists wishlist_delete_own on public.wishlist;
create policy wishlist_delete_own on public.wishlist
for delete to authenticated
using (user_id = '00000000-0000-0000-0000-000000000001'::uuid);

revoke all on public.settings, public.daily_logs, public.rewards, public.achievements, public.wishlist from anon, authenticated;
grant select on public.settings to authenticated;
grant update (reward_name, target_days, theme, daily_reminder_time, show_celebration, enable_sound) on public.settings to authenticated;
grant select on public.daily_logs, public.rewards, public.achievements to authenticated;
grant select, insert, update, delete on public.wishlist to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.unlock_achievements(uuid) from public, anon, authenticated;
revoke all on function public.ensure_user_profile() from public, anon, authenticated;
revoke all on function public.check_in(text, date) from public, anon, authenticated;
revoke all on function public.get_statistics(date) from public, anon, authenticated;
revoke all on function public.get_backup_data() from public, anon, authenticated;
revoke all on function public.restore_backup_data(jsonb) from public, anon, authenticated;

grant execute on function public.ensure_user_profile() to authenticated;
grant execute on function public.check_in(text, date) to authenticated;
grant execute on function public.get_statistics(date) to authenticated;
grant execute on function public.get_backup_data() to authenticated;
grant execute on function public.restore_backup_data(jsonb) to authenticated;

-- All authenticated anonymous sessions are intentionally mapped to the same owner UUID.
-- Anyone who can open the deployed app can therefore view and change this shared data.
-- Direct writes to daily_logs, rewards, and achievements remain restricted to the
-- check_in RPC so streak and reward updates stay atomic.
